### ISSUE TITLE
Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by ebrinkster** [FortyNorthSecurity/EyeWitness#356]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali Linux (kali-rolling latest)

## Pastebin link to error you are encountering
`Message: Unable to find a matching set of capabilities` selenium error for all 

## Expected behavior (vs. what you encountered)
--web does not perform screenshots

## Any additional information
Reinstalled eyewitness package for Kali Linux on 9/25.  When using --web option I get repeat message "Message: Unable to find a matching set of capabilities" for all web services.  Tried using --headless works up until last 5 hosts (and hangs forever).

**Comment by ChrisTruncer** [comment]
This is now fixed, thanks for reporting it!

**Comment by vincentcox** [comment]
I got the same with docker (on mac). 

`docker run --rm -it  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v "$PWD:/tmp/EyeWitness" eyewitness --web -f /tmp/EyeWitness/list.txt --timeout 10`

With output:
```
################################################################################
#                                  EyeWitness                                  #
################################################################################
#           FortyNorth Security - https://www.fortynorthsecurity.com           #
################################################################################

Starting Web Requests (1 Hosts)
Message: Unable to find a matching set of capabilities

Finished in 0.609241008759 seconds
```

**Comment by Thestorm77** [comment]
Same here. Fresh install, parsed_xml.txt file is correct, it processes but get the same message soon after. 

################################################################################
#                                  EyeWitness                                  #
################################################################################
#           FortyNorth Security - https://www.fortynorthsecurity.com           #
################################################################################

Starting Web Requests (3212 Hosts)
Message: Unable to find a matching set of capabilities

Message: Unable to find a matching set of capabilities

Message: Unable to find a matching set of capabilities

Message: Unable to find a matching set of capabilities

Message: Unable to find a matching set of capabilities

Message: Unable to find a matching set of capabilities

Message: Unable to find a matching set of capabilities

Message: Unable to find a matching set of capabilities

Message: Unable to find a matching set of capabilities

Message: Unable to find a matching set of capabilities

Finished in 26.605533123 seconds
[*] No report files found to open, perhaps no hosts were successful

**Comment by ChrisTruncer** [comment]
I just pushed a fix for this, can you test with the latest version of Ubuntu?

**Comment by Thestorm77** [comment]
I tried on both Ubuntu 16.04.5 and 18.04.1 lts with the same result. Got the same error message 
Here are the releases for the Ubuntu versions 

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

====================
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Comment by ChrisTruncer** [comment]
I just tested this on 18.04.1. For Ubuntu, I support the latest LTS version. I tested installed EyeWitness on a clean Ubuntu VM last night, and it successfully installed. I also could successfully run the tool and receive the report.

<img width="1032" alt="running" src="https://user-images.githubusercontent.com/1674822/48094998-d0f58a80-e1d0-11e8-8cec-5818f326b58e.png">

Please look into testing on a clean Ubuntu VM, etc. as I just verified with the latest Ubuntu 18.04.1 release as of yesterday and everything worked.

**Comment by Thestorm77** [comment]
I did install a fresh new instance of ubuntu 18.04.1 in amazon lightsail instance as OS only. Performed apt-get update && apt-get upgrade. Cloned repository, ran install script. Ran Eyewitness and still received the same error. Not sure if it has to do with the LightSail instance or what, but it failed.

**Comment by ChrisTruncer** [comment]
Ok,

It might be something specific in Amazon. I’m not sure what would cause it. But I had downloaded the Ubuntu iso from Ubuntu and made my own vm to test, which was successful. Could you try that?

**Comment by netanelravid** [comment]
I just checked it.
```
docker run --rm -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v "$PWD:/tmp/EyeWitness" eyewitness --single http://www.gmail.com --timeout 10 --headless
```
It seems to work fine.
